import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js Fonts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Next.js Fonts</h1>
        <p>
          Lorem ipsum, <strong>dolor sit amet</strong> consectetur adipisicing
          elit. Dicta cum quaerat quam laborum illo minus ducimus, voluptates
          eligendi repellat consequuntur molestias cumque, ad quos voluptas
          dignissimos voluptatem natus temporibus. Excepturi?
        </p>
      </main>
    </div>
  );
}
